### ISSUE TITLE
Album art off-center when used with Spicetify genre extension

### ISSUE THREAD

**Issue by cpulley** [nimsandu/spicetify-bloom#198]
![image](https://user-images.githubusercontent.com/3003520/221446963-bb8fab66-7de1-481b-ba59-88939a9ede78.png)

When an additional line is added under the title and artist, it causes the album art to get offset a little too far up. I did a little quick testing, and it looks like it fixes itself with this change:

```css
.rVxzkDirgkuRPv5V1HYF, .main-coverSlotCollapsed-container {
    top: auto
}
```

Thanks for the great theme, and I hope you have a chill day!
