### ISSUE TITLE
Devices waking up text is dark gray and hard to read

### ISSUE THREAD

**Issue by jahirfiquitiva** [nimsandu/spicetify-bloom#296]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.16.947.gcfbaa410
- Installed from: Spotify site
- Spicetify version:v2.22.1
- Color scheme: dark
- Extensions: popupLyrics.js, shuffle+.js
- Custom apps: lyrics-plus
- Bloom installation method: Manual
```

### Description

When one opens the `Connect to a device` pop-up / menu for the first time, it takes a second to connect to the devices, and they are listed as `Waking Up`

While they load, the text is dark gray, which makes it really hard to read.

### Screenshots

![Shot 2023-07-28 at 09 56 53@2x](https://github.com/nimsandu/spicetify-bloom/assets/10360816/7710630e-a6ee-4bc8-a6d4-8f665bc52de6)

**Comment by SunsetTechuila** [comment]
I don't have speakers with spotify, so you'll have to give me the element class name yourself
run `spicetify enable-devtools` press `ctrl + shift + i` then `ctrl + shift + c`, click on the element and send the screenshot

**Comment by jahirfiquitiva** [comment]
@SunsetTechuila 

this is the element and classes, but I feel like while they are `Waking up…` they might use an extra or different class, which I wasn't able to screenshot 😕 

![Shot 2023-07-28 at 11 03 29@2x](https://github.com/nimsandu/spicetify-bloom/assets/10360816/1f15a06d-9b1e-490a-9343-f7865567c6ae)

**Comment by SunsetTechuila** [comment]
to catch the list while devices are waking up install [Spicetify Utilities](https://github.com/kyrie25/spicetify-utilities) extension,  enable `Stop Spotify execution with F8` and use it

**Comment by jahirfiquitiva** [comment]
@SunsetTechuila thanks for the advice, here you go

![Shot 2023-07-28 at 11 34 36@2x](https://github.com/nimsandu/spicetify-bloom/assets/10360816/ac07953b-884b-4004-9e91-59c43993db7f)

**Comment by SunsetTechuila** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/1611fefd-f467-4971-8e59-0d4e99c0911e)
does changing the color here affect all the text and icon?

**Comment by jahirfiquitiva** [comment]
@SunsetTechuila it only affects text, the icon is different

![Shot 2023-07-28 at 11 39 52@2x](https://github.com/nimsandu/spicetify-bloom/assets/10360816/9e26b9fa-1cc0-4fd1-b819-aa977a8d3223)

**Comment by SunsetTechuila** [comment]
so I only need these two selectors?
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/c90613b6-813b-49fe-971f-1b1014f79157)

**Comment by jahirfiquitiva** [comment]
@SunsetTechuila I made it like this (edited the css file) just because I'm afraid that random class name might change eventually

```css
.main-devicePicker-devicesList li>button:disabled span,
.main-devicePicker-devicesList li>button[aria-disabled="true"] span {
  color: rgba(255, 255, 255, 0.7) !important;
}

.main-devicePicker-devicesList li>button:disabled .main-devicePicker-nowPlayingActiveIcon,
.main-devicePicker-devicesList li>button[aria-disabled="true"] .main-devicePicker-nowPlayingActiveIcon {
  fill: rgba(255, 255, 255, 0.7) !important;
}
```
